#+TITLE: Potential in Multiplicative Weight Algorithms
#+SETUPFILE: ../../../assets/export.setup

#+BEGIN_QUOTE
This page is a work in progress
#+END_QUOTE

While analyzing multiplicative weight algorithms we track a /potential/ function
keeping the sum of all the expert weights. The idea is kind of intuitive since
it makes sense to track a quantity dependent on the changing variable. Moreover,
its easy to get a lower and upper bound for the sum of weights.

#+BEGIN_aside
A simple weight update technique is of hedging (cite:freund1997decision) where
$w_{i}(t + 1) = w_{i}(t) \beta^{m_i(t)}$. $m_i(t)$ is the loss of expert $i$ at
time $t$ and $\beta$ is a hyper parameter in $[0, 1]$
#+END_aside

In spite of this, the name /potential function/ feels unsatisfactory since the
other connected quantities don't appear anywhere close. A more general and
complete description of this /potential/ appears in cite:cesa2006prediction
(chapter 2). In this description, potential is a wrapper around the sum of
weights $\sum_{i=1}^{n} w_i(t)$ that we usually work with and is written as (in
the exact notation from the book):

\[ \Phi(\mathbf{u}) = \psi\left( \sum_{i=1}^n \phi(u_i) \right) \]

The weights at any time point $t$ is then given by normalizing the vector
$\nabla \Phi(\mathbf{R_{t - 1}})$. Here $\mathbf{R_{t}}$ is the vector of
cumulative regret values for each expert till time $t$.

The question then is, how far can we push this analogy? Definitely we know
something about the derivative of a potential, the negative of which is force.
Multiplying force with displacement results in work.

Now the scalar potential field is on a cumulative risk space. The curvature of
which is well defined if we define the functions $\psi$ and $\phi$. What we
want, in the end, is to minimize the regret. But we can't walk on the regret
landscape directly. We do have some properties about the movements (with the
right set of models) though. One of them is the /Blackwell/ condition which
tells us:

\[ \sup_{y_t \in \mathcal{Y}} \mathbf{r}_t \cdot \nabla \Phi(\mathbf{R}_{t - 1})
\le 0\]

In the physical analogy, this translates to the fact that...

bibliography:./references.bib
