#+TITLE: Aesthetic Alignment
#+TAGS: personal, work

I have spent a fare share of time on a personal interpretation for /meaning of
life/. My current response to the question is that life is meant for us to /enjoy
beauty/. I understand that the response is very contextual and there are [[https://en.wikipedia.org/wiki/Meaning_of_life][many
competing alternatives]]. But the aesthetics answer has always had a strong
personal appeal and also stayed with me for the longest.

There are many kinds of beauties. Few are simple, few are complex. Simple
beauties have more reptilian-brain connections, complex beauties demand more
cognitive effort. You need to spend time to understand and appreciate theatres.
You need to study higher mathematics to appreciate FFTs. Complex beauties are
more rewarding. The deeper you go there, the more /meaningful/ life becomes.

There is a famous Feynman video about beauty of a flower that I find connected
to this idea:

#+HTML: <style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://www.youtube.com/embed/ZbFM3rn4ldo' frameborder='0' allowfullscreen></iframe></div>
#+HTML: <br>

From what I have seen, many /meaningful-life/ pursuits driven by intellect,
emotions, constructed goals and achievements, or anything else, have roots in
one or another source of aesthetic appreciation. If this is my current belief,
it makes sense to rethink how I see systems that I spend a good amount of my
time in, like my profession.

Discussions around /value alignment/ are very common. This is something I have
employed as a tool to understand fits of various kinds in professional setting.
People I work with, teams, projects, or the whole company. I have always found
it to be limited, but didn't have good alternative to think towards. I believe I
have a better answer now: /Aesthetic alignment/. People or systems that are
aesthetically aligned with you share a common framework for aesthetic
appreciation.

#+BEGIN_aside
Of course the differences in training and expertise shouldn't block you from
matching the core philosophies. I have friends from non-technical backgrounds
who align---aesthetically---strongly on aspects we both have been exposed to.
#+END_aside

At a surface level, you can see a lot of alignment. Common training and general
diffusion of ideas help. But diving deeper, towards more complex beauties,
things fall apart. People generally end up aligning on goals, ways of working,
cultural commonalities etc. These are useful but mere proxies for deeper
alignment that shows up only when you inspect complex beauties together.
Whenever I am frustrated, or lost, the distinction shows up more clearly . I
believe I can do better by explicitly deconstructing the interpretation of
aesthetics for each entity I work with, aligning on that, evaluating fit, and
then managing expectations.
