#+TITLE: Aesthetic Alignment
#+SETUPFILE: ../../../../../assets/export.setup
#+TAGS: personal, work

I have spent a fare share of time on a personal interpretation for /meaning of
life/. My current response to the question is that life is meant for us to /enjoy
beauty/. I understand that the response is very contextual and there are [[https://en.wikipedia.org/wiki/Meaning_of_life][many
alternatives]]. But the aesthetics answer has a strong personal appeal and has
stayed with me for the longest.

There are many kinds of beauties. Few are simple, few are complex. Simple
beauties have more reptilian-brain connections, complex beauties demand more
cognitive effort. You need to spend time to understand and appreciate theatres.
You need to study higher mathematics to appreciate FFTs. Many pursuits driven by
intellectual inqueries, emotional expression, constructed goals and
achievements, that fit the bill for meaningful life come from one or other
source of aesthetic appreciation.

There is a famous Feynman video about beauty of a flower that I find connected
to this idea:

#+HTML: <iframe width="650" height="315" src="https://www.youtube-nocookie.com/embed/ZbFM3rn4ldo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

-----

I have heard a lot about /value alignment/. This is something I have employed as a
tool to understand fits of various kinds, mostly in professional setting. I have
always found it to be limited, but didn't have good alternative to think
towards. I believe I have a better answer now, /aesthetic alignment/. People or
systems that are aesthetically aligned with you share common frameworks
aesthetic appreciation.

#+BEGIN_aside
Of course the differences in training and expertise shouldn't block you from
matching the core philosophies. I have friends from non-technical backgrounds
who align---aesthetically---strongly on aspects we both have been exposed to.
#+END_aside

At a surface level, you can see alignment with many people. Common trainings and
general diffusion of ideas help. But diving deeper, towards more complex
beauties, things fall apart. People generally end up aligning on goals, ways of
working, cultural commonalities etc. These are useful but mere proxies for
deeper alignment that shows up only when you inspect complex beauties together.
I believe we can do better by directly deconstructing what aesthetics look for
each of us, aligning on that, and evaluating fit.
