#+TITLE: Pesky Little Things
#+SETUPFILE: ../../assets/export.setup

From whatever I have experienced, there are two kind of mental models provided
by programming tools, /simple/ (e.g. [[http://dplyr.tidyverse.org/][dplyr]]) and /complex/ (e.g. [[https://pandas.pydata.org/][pandas]]). If used
sparingly, most complex tools are really annoying unless, of course, you clearly
understand the idea behind the models they expose. Here are some tools in that
category which I would like to study very /thoroughly/ sometime:

- [ ] Matplotlib. Maybe the recent updates made the API cleaner. A good resource
  to start might be [[http://www.labri.fr/perso/nrougier/teaching/matplotlib/matplotlib.html][this]].
- [ ] $\LaTeX$ is irritating and is almost everywhere. [[http://www.rpi.edu/dept/arc/docs/latex/latex-intro.pdf][Here]] is something that
  might help change my feelings.
- [ ] [[https://sourceforge.net/projects/pgf/][TikZ]]. Inkscape has pretty weak scripting capabilities.
- [X] +Regex. I specifically need to understand how it works to really
  appreciate it.+
- [ ] DNS/CNAMEs/SSLs and everything involved in secure web communication.
- [ ] CSS. Specifically the old layout scheme, flexbox and grid.
