#+TITLE: Really using Org Mode
#+TAGS: productivity

Irrespective of what I tell myself, I have not been using Org mode in its full
glory. The usual problem of file/topic organization is perennial but there are
two really tractable pieces that I haven't given much thought to:

1. Scheduling, along with [[https://orgmode.org/manual/Agenda-commands.html][agenda]]
2. [[https://orgmode.org/manual/Capture.html][Captures]] for quickly getting ideas down

Although these two look independent, the most important/useful scheduling
happens impromptu, just like captures. Keeping a physical notebook has taught me
the importance of capturing things right when you encounter them. Even though a
notebook is the most powerful tool for scribbles and planning, its really bad
for scheduling and capturing since it has a /physical/ form.

So I gave [[http://www.orgzly.com/][orgzly]] another shot and this time its working well, thanks to
[[https://syncthing.net/][syncthing]]. Orgzly's notification system lets me /not avoid/ agenda items since I
don't have to /pull/ up the agenda manually. Having notes nearby also makes it
easy to go both ways:

- capture notes on the go, and
- look at all other files that get regularly ignored since there are always more
  important things to do in a relatively unrestricted machine.

Initially, there was this frustrating issue where you end up updating an org
file at both the places---mobile and laptop---leaving you with git merge
nightmares. I have now enforced one-way write behavior using syncthing and
regular Emacs file variables (~# -*- buffer-read-only: t -*-~). This has more or
less fixed the problem. Hoping to get some mileage with this setup now.
