#+TITLE: Weekly Review /43-2019/
#+SETUPFILE: ../../../../../assets/export.setup
#+PILE: dropcap:nil

#+BEGIN_EXPORT html
<script>
let eventPlotFor = {
week: 43,
year: 2019
}
</script>
<style>
#commit-plot > svg {
height: 600px;
width: 100%;
}
</style>
#+END_EXPORT

#+HTML: <script src="https://d3js.org/d3.v5.min.js"></script>
#+HTML: <script src="../../../../../assets/js/commit-plot.js"></script>

* Experiments
- Tried making a speech to intent system based on phoneme decoding. An
  interesting result, which I was not expecting with low data, was that dense
  representation learning for phonemes help a lot compared to even higher order
  n-grams. My hunch is that looking only at top-1 phoneme transcription is going
  to have high brittleness.

* Readings/Explorations
- [[http://www.nhplace.com/kent/Papers/cl-untold-story.html][Common Lisp: The Untold Story]]. I like the following piece:
#+begin_quote
The charter also identified which projects were in scope and out of scope
for our work, and which were required features and which were optional.

The time spent writing the charter later paid for itself many times over and
it’s an exercise I recommend to any committee engaged in any large endeavor
over a period of time.
#+end_quote
- Metaobject protocols: Why we want them and what else they can do
  (cite:kiczales1993metaobject).
- Explored custom jupyter notebook widgets. The widget framework is really
  useful. I am now trying to move a lot of EDA, tagging etc. systems to widgets.

* Programming
#+HTML: <figure> <div id="commit-plot"></div> <figcaption>
Commits for week 43-2019 and 4 previous weeks.
#+HTML: </figcaption></figure>

* Media
- [[https://aeon.co/ideas/we-have-the-tools-and-technology-to-work-less-and-live-better][We have the tools and technology to work less and live better | Aeon Ideas]]

[[bibliography:./references.bib]]
