#+TITLE: Note Cards
#+SETUPFILE: ../assets/export.setup

#+BEGIN_QUOTE
This page is a work in progress
#+END_QUOTE

(Okay, not exactly cards but I can shuffle entries aroung) Bibliographical
notes. I am realizing their importance /now/ and will be working on this page
fairly regularly.

** TODO 1997 - A decision-theoretic generalization of on-line learning and an application to boosting
 :PROPERTIES:
  :Custom_ID: freund1997decision
  :AUTHOR: Freund \& Schapire
  :JOURNAL: Journal of computer and system sciences
  :YEAR: 1997
  :VOLUME: 55
  :PAGES: 119--139
  :DOI: 
  :URL: 
 :END:

Hello world Pellentesque dapibus suscipit ligula.  Donec posuere augue in quam.
Etiam vel tortor sodales tellus ultricies commodo.  Suspendisse potenti.  Aenean
in sem ac leo mollis blandit.  Donec neque quam, dignissim in, mollis nec,
sagittis eu, wisi.  Phasellus lacus.  Etiam laoreet quam sed arcu.  Phasellus at
dui in ligula mollis ultricies.  Integer placerat tristique nisl.  Praesent
augue.  Fusce commodo.  Vestibulum convallis, lorem a tempus semper, dui dui
euismod elit, vitae placerat urna tortor vitae lacus.  Nullam libero mauris,
consequat quis, varius et, dictum id, arcu.  Mauris mollis tincidunt felis.
Aliquam feugiat tellus ut neque.  Nulla facilisis, risus a rhoncus fermentum,
tellus tellus lacinia purus, et dictum nunc justo sit amet elit
