#+TITLE: White Rhinos, irrationality and other tales
#+TAGS: ramble, skepticism

#+BEGIN_page-intro
White rhinos are down to a few just because irrational persuasions are
effective. Everywhere. Something that might help? Identifying lies.
#+END_page-intro

In case you didn't know '/there are only 3 northern white rhinos left on the
planet/'. There were 5 since I started counting. One died [[http://edition.cnn.com/2015/07/29/world/northern-rhino-dies/][earlier this year]].
Another one, [[http://www.wired.com/2015/11/death-endangered-rhino-leaves-three-world/][last month]]. Its closer relative, southern white rhino, is
relatively safe as of this writing but you never know. Rhinos are ominously
popular targets for poachers. Along with Bengal Tiger (skin) and Elephant
(teeth), this animal (horns) is one of the first that comes to mind when I hear
/poaching/.

Where exactly do the horns go? Having no direct marketing channel, illegal items
are slightly harder to sell (in the usual sense). Although you can create a
market out of thin air, most of the cases require external factors. How about a
bit of /human irrationality/ ?

One of the reasons why Rhinoceros hunting has recently gathered pace is due to a
weird outburst of horn demands from Vietnam. Apparently, there was a [[http://qz.com/82302/theres-a-country-that-will-pay-300000-per-rhino-horn-to-cure-cancer-and-hangovers-and-its-wiping-out-rhinos/][guy]] who was
cured from terminal cancer using rhinoceros horns and people weren't able to
stop the tendency of '/inferring from a sample size of 1/' to outgrow their
rationality.

This brings up an important issue. Not that other reasons for dwindling wildlife
are not so important, but because /this/ specific reason is prevalent in every
other area to an extent you would probably always underestimate.

* Quacks, Advertisements and Lies
Recently, I got home, started watching TV, and one thing i noticed is that /our
situation, in India, isn't drastically different from Vietnam/. I have seen
traditional Chinese medicine usually getting the heat for promoting irrational
cultural beliefs (sadly, many involving endangered species). Are we any better?

Natural remedies are inspiring. And to be very clear, I have a space of respect
for them (I mean, why not?). But I never quite understand the /point of view/ of
many of their propagators here. When engaged in discussion, most of them try to
sell one of the following conclusions:

- Western medicine is trying to destroy our traditional wisdom
- People in ancient times were much healthier
- We have a long history with medicine

Honestly, I have stopped paying attention to statements which don't add anything
in anyone's plate. So, I ask, tell me what /you/ are proposing? And I get
statements like this (not disclosing the source)

#+BEGIN_QUOTE
  vegetarian food reduces domestic violence.
#+END_QUOTE

Now, it's not about the people who can /cure/ homosexuality, the one who can tell
we are going to die in future, the one who can guarantee 700% reduction in fat
or the realists with a conservative 100%. It is about how /we/ see these events
and infer. I will be willing to believe the given statement if the person who is
promoting this /knowledge/ can answer following questions affirmatively.

* Few Simple Questions

#+BEGIN_QUOTE
At school you were taught about chemicals in test tubes, equations to describe
motion, and maybe something on photosynthesis---about which more later---but in
all likelihood you were taught nothing about death, risk, statistics, and the
science of what will kill or cure you.

#+HTML:<footer>Ben Goldacre - Bad Science (2008)</footer>
#+END_QUOTE

Here are a few simple questions (non-exhaustive, please email me to add/remove
things) I believe we should be asking to judge the conclusions of a research.
Since researches on medicine and likes involve comparison and statistical
testings, these are not exactly valid for /any/ research.

** What do the numbers mean?
No, not what you are being told. What the numbers /actually/ mean? Here is a case.

In a test on N (N/2, N/2) people, product A performed 50% better than product B
(assume an effect).

What is /50%/ here?

- Is there a performance metric which bumps 50% more for A guys (first N/2, say)
  than for B guys (next N/2)?
- Is it a mean (max, median) of that metric for groups?
- Or, is it slightly quirky like "it worked for 50% more guys"?

** Can I reproduce the numbers?
Good research is reproducible research. Given an array of results, access to
research documentations and methodologies, a person should be able to get to the
same conclusions as published.

/Once done, there is a more critical question. This should be up in the order,
but most of the times Q1 and Q2 hit it right./

** Is the process fair?
Now since the documented methods are providing the expected results, is the
method actually performing a fair test?

For example if you want to compare two toothpastes, you will want to have few
basic things like:

- Two /randomly/ divided groups
- Doubly blinded experiment
- No confounding variables etc.

Also, is the research using sufficient sample size? Are the numbers compared
properly using established statistical tests? etc.

--------------

If you see the previous statement (about domestic violence) as a research
outcome (which is the only reason you should be believing it), then you can
immediately identify what might be wrong in the experiment (spoiler:
/everything/). When you are communicating via a proper scientific channel, you are
automatically bound to go ahead only when the results are conclusive. But when
statements like this start to frame the basis of judgments, you know the channel
of knowledge generation and communication is severely damaged. I have heard so
many people (due to their own personal reasons) around me agreeing on similar
issues like '/media torturing and twisting facts/'. Yet, shockingly small number
of people criticize these incidences of quackery with similar enthusiasm.

#+BEGIN_QUOTE
The idea is to try and give all the information to help others to judge
the value of your contribution; not just the information that leads to
judgment in one particular direction or another.

#+HTML:<footer>Richard P. Feynman</footer>
#+END_QUOTE

Many argue that it's important to use dumbed down logic to reach a mass
audience. But, there is a difference between /dumbed down/ and /simplified/. One
misleads people in thinking /they know the actual thing/ while the other make them
realize /what they don't know/.

The major problems with the propagators are probably not the numerous questions
raised, but the ones unanswered because their claims are /unfalsifiable/. This
approach is not a sane way to do any Science. Most of the claimed success is due
to the confounding variables covering the obvious observations like /eating
healthy helps/. Others left are weeded out in a huge placebo storm.

Many a times, you /can't avoid/ irrationality. But, sometimes you /can't afford/.
There is a huge responsibility on you when you are touching dead serious topics
involving lives, deaths and crowd emotions. We can't afford statements like
/"AIDS can be cured through yoga"/, but while we can, let's ask if these
statements have enough evidence to answer the questions.

--------------

Before finishing, I would strongly recommend reading [[https://www.goodreads.com/book/show/3272165-bad-science][Bad Science]] by Ben Goldacre
(the quotes in this post are directly taken from there), specially the chapter
'/The Doctor Will Sue You Now/' if you are on a tight schedule. The story in the
chapter explains the exact conundrum here with amazing precision and is
downright serious.

I wrote this post because of the following few reasons, none of which involve
initiating a /hate debate/ against any of the specific ideas mentioned.

- I felt like I should.
- I still see many of my friends, relatives and myself reacting to senseless
  persuasions. So at its worst, this post can simply work as a sanity reminder
  for me.
- Maybe I am just ashamed of what our species has done to rhinos.

And sadly, the rhinoceros count is not the only thing thats going down.

#+BEGIN_edits
- Thanks Gopal Sharma for suggesting ammendments to the list and other [[https://github.com/lepisma/lepisma.github.io/commit/c7aede536fbd2306e6172ccf35499b17e9807518][fixes]].
#+END_edits
