#+TITLE: Reference Management
#+SETUPFILE: ../../assets/export.setup

I used to rely on [[http://www.mendeley.com/][mendeley]] for working with BibTeX related things. After
switching mostly to Emacs, I find mendeley a bit confining. This page documents
my Emacs based setup as of now. I will be updating it with new things that I
try.

There are a few pieces in the process of managing references.
1. Searching/adding papers/documents
2. Using the BibTeX entries
3. Working with pdf annotations/notes

* Searching
Mendeley and similar tools have decent support for step 1 and 2. The way I had
been using mendeley was to use its /capture/ feature and make it output a single
~~/library.bib~ file which can then be read by Emacs.

The literature search feature from mendeley can be replicated if you get an
interface to Google Scholar and few other aggregators. Turns out there is a
package exactly for that, [[https://github.com/cute-jumper/gscholar-bibtex][gscholar-bibtex]], which lets you search documents and
add BibTeX entries in a single file as you would have been doing with mendeley.

* Using references
Not much to say here. [[https://github.com/jkitchin/org-ref][org-ref]] is a very feature complete solution for working
with references in Org files. I am managing the following three locations using
it:

- The main bibliography file, ~org-ref-default-bibliography~. The helm functions
  from org-ref make it really easy to search and add citations.


- Notes file, ~org-ref-bibliography-notes~. I am starting to keep a notes file
  (lives [[pile:readings/bib-notes][here]]) which will help me trace/organize ideas and also make the
  citations more meaningful rather than just pushing a ~[1], [2], [3], [4]~ list.


- PDFs in ~org-ref-pdf-directory~. PDFs kept here are picked up by org-ref
  allowing you to open/send email etc. Since pdf download features requires more
  metadata (at least DOI, if I read it right), I am keeping it a bit manual as
  of now.

Cross linking items is easy since they all are keyed by their cite-keys. Plus
there are functions to extract document specific bibliographies so that I can
keep pages here self contained.

* Annotations
Although Emacs has a really decent pdf reading facility in [[https://github.com/politza/pdf-tools][pdf-tools]] now, it
still provides a brittle experience. Text selection and scrolling doesn't feel
as good as your regular pdf reader.

I am now using [[https://okular.kde.org/][okular]] for reading all non plain text documents. It comes with
really good support for file extensions and has complete annotation tooling
(plus I am a KDE refuge). For seamlessly working with Emacs, I found [[https://bitbucket.org/jpkotta/openwith][openwith]]
really useful.

* Missing pieces
Here are a few things that I would like to setup when I have some time. Most
likely there already are tools for these which I am unaware of.

1. /Browser capture/

   Capturing papers from browser one of the most useful features of mendeley.
   Shouldn't be that hard to cook considering the [[https://github.com/jkitchin/org-ref#some-other-useful-libraries-in-org-ref][many utilities]] for working
   with different websites available in org-ref.

2. /PDF management/

   I tried [[https://github.com/alejandrogallo/papis][papis]] but it doesn't provide a lot if you already have a bib thing
   going. Since most of the pdfs will be (somewhat) curated, I think a few basic
   functions would do just fine.
