#+TITLE: Who is a Philosopher?
#+TAGS: personal

Somewhere in class 2, 3 or 4 [fn::Indian Education system. I remember the school
and context this was set in. Possibly class 3 but keeping a margin of error.], I
remember a moment when one of my teachers said the following on the question of
who is a philosopher?[fn::I am sure no one from the students asked this. It was
mostly a class on various professions and what they mean, things like 'butcher',
'carpenter' etc.]

#+begin_quote
A person who thinks why something happens.
#+end_quote

Then comes the moment of magic. He moved a wooden ruler from one place to
another and said:

#+begin_quote
A philosopher will think why this moved.
#+end_quote

My first reaction was of intrigue. What does that mean? /To think/. I am pretty
sure I didn't follow the train of thought personally since I was too young to
focus on things for long, but I preserved the moment in memory somehow. And this
moment keeps coming back to me every few years reminding how very insightful
that demonstration of displaced ruler was. There are layers and layers to its
understanding and, most importantly, you can clearly see that these are there to
be pealed off.

Of course the definition is too restrictive considering all the fundamental
questions philosophy attempts to answer but this was a beautifully insightful
act, free from a very simplistic physical-processes viewpoint that was used for
all other professions in that class.
