#+TITLE: Plan like an Engineer
#+TAGS: work

People at management level usually disregard engineers' planning capabilities.
They say engineers /work/ at lower levels and therefore are not great at observing
high level issues, this makes them bad at thinking and planning. While this
argument is correct in its own way, it implies that thinking and planning are
skills that are only developed once you are working at a higher level of
abstraction.

I have had drastically different experiences. I have seen some of the best acts
of thinking and planning done among my engineering peers. And it's beyond scale
of scope, or time, or impact. I am talking about the core techniques. Just based
on their training and work, engineers are better positioned to manage
complexity, keep promises, understand when and where things are not going well.

I have seen many projects fail because tasks were not tracked properly, people
didn't know what exactly to do, targets were not well defined, vague promises
were floated, ownership was not defined, and similar fundamental issues. While
you might not get a complete enough answer from a non-engineer person, there are
simple answers for these in any engineer's workflow.

After observing multiple cases validating what I have written above, I have
learned to trust the planning mindset inherent in engineers rather than trying
to uncover a revelation in non-engineers, even for non-engineering projects.
