#+TITLE: Productivity
#+SETUPFILE: ../../assets/export.setup

In this tree I will document my time management and related workflow.

If you have been following my blog or journal or log you might know about
numerous attempts at better time utilization. Most of them failed because of a
few reasons, also documented.

Recently I have been trying to be more aware of the issues and have come to the
conclusion that focusing on time and stuff is sorta back-pedalling. I thought a
little more about it and came with the following summary of the approach I am
trying to go with next:

#+begin_quote
Plan like a general, work like an artist.
#+end_quote

Of course the definitions of 'general' and 'artist' are the stereotypical one.
The idea is to have a good framework for knowing categorizing various acts of
planning, but still keep the working part very flexible. The framework below
follows an internal talk on /A Vocabulary for Productivity/ [[https://github.com/Vernacular-ai/talks/tree/master/vocab-productivity][here]].

Inspired by the [[https://en.wikipedia.org/wiki/Getting_Things_Done][GTD]] structure, I try to look at the following acts while
working:

1. Capture
2. Organize
3. View
4. Work
5. Review

All of these tie to two other tools that I am trying to use more. One is
Org-Mode, other is OKRs. Org helps in the working regularly with the 5 steps and
provides every kind of assistance that I need. OKRs help in setting more long
term directions to align these acts.

Here is a [[https://rework.withgoogle.com/guides/set-goals-with-okrs/steps/introduction/][good document]] on OKRs.
